#theme = "gruvbox_material_light_hard"
theme = "gruvbox_light_mod"

[editor]
cursorline = true
completion-replace = true
bufferline = "always"
color-modes = true
trim-final-newlines = true

[editor.clipboard-provider.custom]
yank = { command = "pbpaste" }
paste = { command = "pbcopy" }
primary-yank = { command = "pbpaste" }
primary-paste = { command = "pbcopy" }

# [editor.lsp]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace.render]
space = "none"
nbsp = "all"
nnbsp = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "␣"
nnbsp = "⍽"
tab = "»"
newline = "⏎"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.smart-tab]
enable = true

[keys.insert]
C-a = "goto_line_start"
C-e = "goto_line_end_newline"
