# 2025-09-24
# https://github.com/helix-editor/helix/blob/master/languages.toml
# tomlq ".language[].name" languages.toml | sed 's/^\(.*\)$/\[\[language\]\]\nname = \1\nindent = \{ tab-width = 4, unit = "\\\\t" \}\n/'

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "sway"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "toml"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "awk"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "protobuf"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "textproto"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "elixir"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "fennel"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "fish"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "mint"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "mojo"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "janet"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "json"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "jsonc"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "json-ld"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "json5"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "crystal"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "c-sharp"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cel"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "spicedb"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "go"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gomod"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gotmpl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gowork"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "jsx"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "typespec"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "tsx"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "css"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "scss"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "html"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "htmldjango"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "python"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "nickel"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "nix"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ruby"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "php"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "php-only"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "blade"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "twig"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "latex"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "bibtex"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "lean"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "lpf"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "julia"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "java"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "smali"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ledger"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "beancount"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ocaml"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ocaml-interface"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "dune"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "lua"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "teal"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "svelte"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "vue"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "yaml"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "nestedtext"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "haskell"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "haskell-persistent"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "purescript"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "zig"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "prolog"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "tsq"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cmake"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "make"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "glsl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "perl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "pod"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "racket"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "common-lisp"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "comment"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "wesl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "wgsl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "llvm"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "llvm-mir"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "llvm-mir-yaml"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "tablegen"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "mail"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "markdown-rustdoc"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "markdown.inline"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "djot"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "dart"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "scala"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "dockerfile"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "docker-compose"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "git-commit"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "git-notes"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "diff"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "git-rebase"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "regex"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "git-config"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "git-attributes"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "git-ignore"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "graphql"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "elm"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "iex"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "rescript"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "erlang"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "kotlin"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "hcl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "tfvars"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "org"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "solidity"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gleam"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "quarto"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ron"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "robot"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "r"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "rmarkdown"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "swift"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "erb"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ejs"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "eex"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "heex"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "sql"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gdscript"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "godot-resource"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "nu"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "vala"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "hare"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "devicetree"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cairo"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cpon"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "odin"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "meson"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "sshclientconfig"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "scheme"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "v"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "verilog"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "edoc"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "jsdoc"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "openscad"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "prisma"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "clojure"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "starlark"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "elvish"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "idris"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "fortran"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ungrammar"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "dot"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cue"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "slang"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "slint"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "task"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "xit"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "esdl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "pascal"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "sml"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "jsonnet"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ada"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "astro"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "bass"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "wat"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "wast"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "d"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "vhs"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "kdl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "xml"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "dtd"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "wit"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "env"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "systemd"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ini"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "inko"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "bicep"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "qml"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "mermaid"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "matlab"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ponylang"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "dhall"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "sage"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "msbuild"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "pem"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "passwd"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "hosts"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "uxntal"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "yuck"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "prql"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "po"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "nasm"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gas"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "rst"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "capnp"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "smithy"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "vhdl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "rego"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "nim"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cabal"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "hurl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "markdoc"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "opencl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "just"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gn"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "blueprint"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "forth"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "fsharp"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "t32"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "webc"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "typst"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "nunjucks"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "jinja"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "jjdescription"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "jq"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "wren"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "unison"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "todotxt"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "strace"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gemini"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "agda"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "templ"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "dbml"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "bitbake"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "log"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "hoon"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "hocon"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "koka"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "tact"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "pkl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "groovy"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "fidl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "powershell"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ld"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "hyprlang"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "tcl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "supercollider"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "pkgbuild"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "helm"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "glimmer"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ohm"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "earthfile"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "adl"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ldif"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "xtc"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "move"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "pest"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "elisp"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gjs"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gts"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gherkin"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "thrift"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "circom"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "snakemake"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cylc"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "quint"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "spade"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "amber"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "koto"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gpr"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "vento"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "nginx"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "codeql"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gren"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ghostty"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "tera"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "fga"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "csv"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "yara"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "ink"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "sourcepawn"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "tlaplus"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "werk"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "debian"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "pug"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "dunstrc"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "rust-format-args"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "rust-format-args-macro"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "clarity"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "alloy"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "luau"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "caddyfile"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "properties"
indent = { tab-width = 4, unit = "\t" }

