# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@noble/curves-1.4.2" = {
      name = "_at_noble_slash_curves";
      packageName = "@noble/curves";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@noble/curves/-/curves-1.4.2.tgz";
        sha512 = "TavHr8qycMChk8UwMld0ZDRvatedkzWfH8IiaeGCfymOP5i0hSCozz9vHOL0nkwk7HRMlFnAiKpS2jrUmSybcw==";
      };
    };
    "@noble/curves-1.8.2" = {
      name = "_at_noble_slash_curves";
      packageName = "@noble/curves";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@noble/curves/-/curves-1.8.2.tgz";
        sha512 = "vnI7V6lFNe0tLAuJMu+2sX+FcL14TaCWy1qiczg1VwRmPrpQCdq5ESXQMqUc2tluRNf6irBXrWbl1mGN8uaU/g==";
      };
    };
    "@noble/hashes-1.4.0" = {
      name = "_at_noble_slash_hashes";
      packageName = "@noble/hashes";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@noble/hashes/-/hashes-1.4.0.tgz";
        sha512 = "V1JJ1WTRUqHHrOSh597hURcMqVKVGL/ea3kv0gSnEdsEZ0/+VyPghM1lMNGc00z7CIQorSvbKpuJkxvuHbvdbg==";
      };
    };
    "@noble/hashes-1.7.2" = {
      name = "_at_noble_slash_hashes";
      packageName = "@noble/hashes";
      version = "1.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@noble/hashes/-/hashes-1.7.2.tgz";
        sha512 = "biZ0NUSxyjLLqo6KxEJ1b+C2NAx0wtDoFvCaXHGgUkeHzf3Xc1xKumFKREuT7f7DARNZ/slvYUwFG6B0f2b6hQ==";
      };
    };
    "@nomicfoundation/edr-0.12.0-next.14" = {
      name = "_at_nomicfoundation_slash_edr";
      packageName = "@nomicfoundation/edr";
      version = "0.12.0-next.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/edr/-/edr-0.12.0-next.14.tgz";
        sha512 = "MGHY2x7JaNdkqlQxFBYoM7Miw2EqsQrI3ReVZMwLP5mULSRTAOnt3hCw6cnjXxGi991HnejNAedJofke6OdqqA==";
      };
    };
    "@nomicfoundation/edr-darwin-arm64-0.12.0-next.14" = {
      name = "_at_nomicfoundation_slash_edr-darwin-arm64";
      packageName = "@nomicfoundation/edr-darwin-arm64";
      version = "0.12.0-next.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/edr-darwin-arm64/-/edr-darwin-arm64-0.12.0-next.14.tgz";
        sha512 = "sl0DibKSUOS7JXhUtaQ6FJUY+nk+uq5gx+Fyd9iiqs8awZPNn6KSuvV1EbWCi+yd3mrxgZ/wO8E77C1Dxj4xQA==";
      };
    };
    "@nomicfoundation/edr-darwin-x64-0.12.0-next.14" = {
      name = "_at_nomicfoundation_slash_edr-darwin-x64";
      packageName = "@nomicfoundation/edr-darwin-x64";
      version = "0.12.0-next.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/edr-darwin-x64/-/edr-darwin-x64-0.12.0-next.14.tgz";
        sha512 = "lfmatc1MSOaw0rDFB+ynnAGz5TWm3hSeY/+zDpPZghMODZelXm4JCqF41CQ6paLsW3X/pXcHM1HUGCUBWeoI/A==";
      };
    };
    "@nomicfoundation/edr-linux-arm64-gnu-0.12.0-next.14" = {
      name = "_at_nomicfoundation_slash_edr-linux-arm64-gnu";
      packageName = "@nomicfoundation/edr-linux-arm64-gnu";
      version = "0.12.0-next.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/edr-linux-arm64-gnu/-/edr-linux-arm64-gnu-0.12.0-next.14.tgz";
        sha512 = "sWun3PhVgat8d4lg1d5MAXSIsFlSMBzvrpMSDFNOU9hPJEclSHbHBMRcarQuGqwm/5ZBzTwCS25u78A+UATTrg==";
      };
    };
    "@nomicfoundation/edr-linux-arm64-musl-0.12.0-next.14" = {
      name = "_at_nomicfoundation_slash_edr-linux-arm64-musl";
      packageName = "@nomicfoundation/edr-linux-arm64-musl";
      version = "0.12.0-next.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/edr-linux-arm64-musl/-/edr-linux-arm64-musl-0.12.0-next.14.tgz";
        sha512 = "omWKioD8fFp7ayCeSDu2CqvG78+oYw8zdVECDwZVmE0jpszRCsTufNYflWRQnlGqH6GqjEUwq2c3yLxFgOTjFg==";
      };
    };
    "@nomicfoundation/edr-linux-x64-gnu-0.12.0-next.14" = {
      name = "_at_nomicfoundation_slash_edr-linux-x64-gnu";
      packageName = "@nomicfoundation/edr-linux-x64-gnu";
      version = "0.12.0-next.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/edr-linux-x64-gnu/-/edr-linux-x64-gnu-0.12.0-next.14.tgz";
        sha512 = "vk0s4SaC7s1wa98W24a4zqunTK/yIcSEnsSLRM/Nl+JJs6iqS8tvmnh/BbFINORMBJ065OWc10qw2Lsbu/rxtg==";
      };
    };
    "@nomicfoundation/edr-linux-x64-musl-0.12.0-next.14" = {
      name = "_at_nomicfoundation_slash_edr-linux-x64-musl";
      packageName = "@nomicfoundation/edr-linux-x64-musl";
      version = "0.12.0-next.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/edr-linux-x64-musl/-/edr-linux-x64-musl-0.12.0-next.14.tgz";
        sha512 = "/xKQD6c2RXQBIb30iTeh/NrMdYvHs6Nd+2UXS6wxlfX7GzRPOkpVDiDGD7Sda82JI459KH67dADOD6CpX8cpHQ==";
      };
    };
    "@nomicfoundation/edr-win32-x64-msvc-0.12.0-next.14" = {
      name = "_at_nomicfoundation_slash_edr-win32-x64-msvc";
      packageName = "@nomicfoundation/edr-win32-x64-msvc";
      version = "0.12.0-next.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/edr-win32-x64-msvc/-/edr-win32-x64-msvc-0.12.0-next.14.tgz";
        sha512 = "GZcyGdOoLWnUtfPU+6B1vUi4fwf3bouSRf3xuKFHz3p/WNhpDK+8Esq3UmOmYAZWRgFT0ZR6XUk9H2owGDTVvQ==";
      };
    };
    "@nomicfoundation/hardhat-errors-3.0.5" = {
      name = "_at_nomicfoundation_slash_hardhat-errors";
      packageName = "@nomicfoundation/hardhat-errors";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/hardhat-errors/-/hardhat-errors-3.0.5.tgz";
        sha512 = "8Ayqf6hFM1glmrSxrXgX6n2pn5uTlHNxEB8N5Me0DOeOGB67PRIrQdiO+RzUhrNW5YgWUNWBevOLQbW06uQ79g==";
      };
    };
    "@nomicfoundation/hardhat-utils-3.0.5" = {
      name = "_at_nomicfoundation_slash_hardhat-utils";
      packageName = "@nomicfoundation/hardhat-utils";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/hardhat-utils/-/hardhat-utils-3.0.5.tgz";
        sha512 = "5zkQSuSxkwK7fQxKswJ1GGc/3AuWBSmxA7GhczTPLx28dAXQnubRU8nA48SkCkKesJq5x4TROP+XheSE2VkLUA==";
      };
    };
    "@nomicfoundation/hardhat-zod-utils-3.0.1" = {
      name = "_at_nomicfoundation_slash_hardhat-zod-utils";
      packageName = "@nomicfoundation/hardhat-zod-utils";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/hardhat-zod-utils/-/hardhat-zod-utils-3.0.1.tgz";
        sha512 = "I6/pyYiS9p2lLkzQuedr1ScMocH+ew8l233xTi+LP92gjEiviJDxselpkzgU01MUM0t6BPpfP8yMO958LDEJVg==";
      };
    };
    "@nomicfoundation/solidity-analyzer-0.1.2" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer";
      packageName = "@nomicfoundation/solidity-analyzer";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer/-/solidity-analyzer-0.1.2.tgz";
        sha512 = "q4n32/FNKIhQ3zQGGw5CvPF6GTvDCpYwIf7bEY/dZTZbgfDsHyjJwURxUJf3VQuuJj+fDIFl4+KkBVbw4Ef6jA==";
      };
    };
    "@scure/base-1.1.9" = {
      name = "_at_scure_slash_base";
      packageName = "@scure/base";
      version = "1.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@scure/base/-/base-1.1.9.tgz";
        sha512 = "8YKhl8GHiNI/pU2VMaofa2Tor7PJRAjwQLBBuilkJ9L5+13yVbC7JO/wS7piioAvPSwR3JKM1IJ/u4xQzbcXKg==";
      };
    };
    "@scure/base-1.2.6" = {
      name = "_at_scure_slash_base";
      packageName = "@scure/base";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@scure/base/-/base-1.2.6.tgz";
        sha512 = "g/nm5FgUa//MCj1gV09zTJTaM6KBAHqLN907YVQqf7zC49+DcO4B1so4ZX07Ef10Twr6nuqYEH9GEggFXA4Fmg==";
      };
    };
    "@scure/bip32-1.4.0" = {
      name = "_at_scure_slash_bip32";
      packageName = "@scure/bip32";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@scure/bip32/-/bip32-1.4.0.tgz";
        sha512 = "sVUpc0Vq3tXCkDGYVWGIZTRfnvu8LoTDaev7vbwh0omSvVORONr960MQWdKqJDCReIEmTj3PAr73O3aoxz7OPg==";
      };
    };
    "@scure/bip39-1.3.0" = {
      name = "_at_scure_slash_bip39";
      packageName = "@scure/bip39";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@scure/bip39/-/bip39-1.3.0.tgz";
        sha512 = "disdg7gHuTDZtY+ZdkmLpPCk7fxZSu3gBiEGuoC1XYxv9cGx3Z6cpTggCgW6odSOOIXCiDjuGejW+aJKCY/pIQ==";
      };
    };
    "@sentry/core-9.47.1" = {
      name = "_at_sentry_slash_core";
      packageName = "@sentry/core";
      version = "9.47.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/core/-/core-9.47.1.tgz";
        sha512 = "KX62+qIt4xgy8eHKHiikfhz2p5fOciXd0Cl+dNzhgPFq8klq4MGMNaf148GB3M/vBqP4nw/eFvRMAayFCgdRQw==";
      };
    };
    "@streamparser/json-0.0.22" = {
      name = "_at_streamparser_slash_json";
      packageName = "@streamparser/json";
      version = "0.0.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/@streamparser/json/-/json-0.0.22.tgz";
        sha512 = "b6gTSBjJ8G8SuO3Gbbj+zXbVx8NSs1EbpbMKpzGLWMdkR+98McH9bEjSz3+0mPJf68c5nxa3CrJHp5EQNXM6zQ==";
      };
    };
    "@streamparser/json-node-0.0.22" = {
      name = "_at_streamparser_slash_json-node";
      packageName = "@streamparser/json-node";
      version = "0.0.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/@streamparser/json-node/-/json-node-0.0.22.tgz";
        sha512 = "sJT2ptNRwqB1lIsQrQlCoWk5rF4tif9wDh+7yluAGijJamAhrHGYpFB/Zg3hJeceoZypi74ftXk8DHzwYpbZSg==";
      };
    };
    "adm-zip-0.4.16" = {
      name = "adm-zip";
      packageName = "adm-zip";
      version = "0.4.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/adm-zip/-/adm-zip-0.4.16.tgz";
        sha512 = "TFi4HBKSGfIKsK5YCkKaaFG2m4PEDyViZmEwof3MTIgzimHLto6muaHVpbrljdIvIrFZzEq/p4nafOeLcYegrg==";
      };
    };
    "ansi-colors-4.1.3" = {
      name = "ansi-colors";
      packageName = "ansi-colors";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-colors/-/ansi-colors-4.1.3.tgz";
        sha512 = "/6w/C21Pm1A7aZitlI5Ni/2J6FFQN8i1Cvz3kHABAAbw93v/NlvKdVOqz7CCWz/3iv/JplRSEEZ83XION15ovw==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "bufferutil-4.0.9" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.9.tgz";
        sha512 = "WDtdLmJvAuNNPzByAYpRo2rF1Mmradw6gvWsQKf63476DDXmomT9zUiGypLcG4ibIM67vhAj8jJRdbmEws2Aqw==";
      };
    };
    "chalk-5.6.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "5.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-5.6.2.tgz";
        sha512 = "7NzBL0rN6fMUW+f7A6Io4h40qQlG+xGmtMxfbnH/K7TAtt8JQWVQK+6g0UXKMeVJoyV5EkkNsErQ8pVD3bLHbA==";
      };
    };
    "chokidar-4.0.3" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-4.0.3.tgz";
        sha512 = "Qgzu8kfBvo+cA4962jnP1KkS6Dop5NS6g7R5LFYJr4b8Ub94PPQXUksCw9PvXoeXPRRddRNC5C1JQUR2SMGtnA==";
      };
    };
    "debug-4.4.3" = {
      name = "debug";
      packageName = "debug";
      version = "4.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.4.3.tgz";
        sha512 = "RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==";
      };
    };
    "enquirer-2.4.1" = {
      name = "enquirer";
      packageName = "enquirer";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/enquirer/-/enquirer-2.4.1.tgz";
        sha512 = "rRqJg/6gd538VHvR3PSrdRBb/1Vy2YfzHqzvbhGIQpDRKIa4FgV/54b5Q1xYSxOOwKvjXweS26E0Q+nAMwp2pQ==";
      };
    };
    "env-paths-2.2.1" = {
      name = "env-paths";
      packageName = "env-paths";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/env-paths/-/env-paths-2.2.1.tgz";
        sha512 = "+h1lkLKhZMTYjog1VEpJNG7NZJWcuc2DDk/qsqSTRRCOXiLjeQ1d1/udrUGhqMxUgAlwKNZ0cf2uqan5GLuS2A==";
      };
    };
    "esbuild-0.25.12" = {
      name = "esbuild";
      packageName = "esbuild";
      version = "0.25.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild/-/esbuild-0.25.12.tgz";
        sha512 = "bbPBYYrtZbkt6Os6FiTLCTFxvq4tt3JKall1vRwshA3fdVztsLAatFaZobhkBC8/BrPetoa0oksYoKXoG4ryJg==";
      };
    };
    "ethereum-cryptography-2.2.1" = {
      name = "ethereum-cryptography";
      packageName = "ethereum-cryptography";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ethereum-cryptography/-/ethereum-cryptography-2.2.1.tgz";
        sha512 = "r/W8lkHSiTLxUxW8Rf3u4HGB0xQweG2RyETjywylKZSzLWoWAijRz8WCuOtJ6wah+avllXBqZuk29HCCvhEIRg==";
      };
    };
    "fast-equals-5.3.3" = {
      name = "fast-equals";
      packageName = "fast-equals";
      version = "5.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-equals/-/fast-equals-5.3.3.tgz";
        sha512 = "/boTcHZeIAQ2r/tL11voclBHDeP9WPxLt+tyAbVSyyXuUFyh0Tne7gJZTqGbxnvj79TjLdCXLOY7UIPhyG5MTw==";
      };
    };
    "get-tsconfig-4.13.0" = {
      name = "get-tsconfig";
      packageName = "get-tsconfig";
      version = "4.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-tsconfig/-/get-tsconfig-4.13.0.tgz";
        sha512 = "1VKTZJCwBrvbd+Wn3AOgQP/2Av+TfTCOlE4AcRJE72W1ksZXbAx8PPBR9RzgTeSPzlPMHrbANMH3LbltH73wxQ==";
      };
    };
    "json-stream-stringify-3.1.6" = {
      name = "json-stream-stringify";
      packageName = "json-stream-stringify";
      version = "3.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stream-stringify/-/json-stream-stringify-3.1.6.tgz";
        sha512 = "x7fpwxOkbhFCaJDJ8vb1fBY3DdSa4AlITaz+HHILQJzdPMnHEFjxPwVUi1ALIbcIxDE0PNe/0i7frnY8QnBQog==";
      };
    };
    "micro-eth-signer-0.14.0" = {
      name = "micro-eth-signer";
      packageName = "micro-eth-signer";
      version = "0.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micro-eth-signer/-/micro-eth-signer-0.14.0.tgz";
        sha512 = "5PLLzHiVYPWClEvZIXXFu5yutzpadb73rnQCpUqIHu3No3coFuWQNfE5tkBQJ7djuLYl6aRLaS0MgWJYGoqiBw==";
      };
    };
    "micro-packed-0.7.3" = {
      name = "micro-packed";
      packageName = "micro-packed";
      version = "0.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/micro-packed/-/micro-packed-0.7.3.tgz";
        sha512 = "2Milxs+WNC00TRlem41oRswvw31146GiSaoCT7s3Xi2gMUglW5QBeqlQaZeHr5tJx9nm3i57LNXPqxOOaWtTYg==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "node-gyp-build-4.8.4" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.8.4.tgz";
        sha512 = "LA4ZjwlnUblHVgq0oBF3Jl/6h/Nvs5fzBLwdEF4nuxnFdsfajde4WfxtJr3CaiH+F6ewcIB/q4jQ4UzPyid+CQ==";
      };
    };
    "p-map-7.0.4" = {
      name = "p-map";
      packageName = "p-map";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-map/-/p-map-7.0.4.tgz";
        sha512 = "tkAQEw8ysMzmkhgw8k+1U/iPhWNhykKnSk4Rd5zLoPJCuJaGRPo6YposrZgaxHKzDHdDWWZvE/Sk7hsL2X/CpQ==";
      };
    };
    "readdirp-4.1.2" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-4.1.2.tgz";
        sha512 = "GDhwkLfywWL2s6vEjyhri+eXmfH6j1L7JE27WhqLeYzoh/A3DBaYGEj2H/HFZCn/kMfim73FXxEJTw06WtxQwg==";
      };
    };
    "resolve-pkg-maps-1.0.0" = {
      name = "resolve-pkg-maps";
      packageName = "resolve-pkg-maps";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-pkg-maps/-/resolve-pkg-maps-1.0.0.tgz";
        sha512 = "seS2Tj26TBVOC2NIc2rOe2y2ZO7efxITtLZcGSOnHHNOQ7CkiUBfw0Iw2ck6xkIhPwLhKNLS8BO+hEpngQlqzw==";
      };
    };
    "resolve.exports-2.0.3" = {
      name = "resolve.exports";
      packageName = "resolve.exports";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve.exports/-/resolve.exports-2.0.3.tgz";
        sha512 = "OcXjMsGdhL4XnbShKpAcSqPMzQoYkYyhbEaeSko47MjRP9NfEQMhZkXL1DoFlt9LWQn4YttrdnV6X2OiyzBi+A==";
      };
    };
    "rfdc-1.4.1" = {
      name = "rfdc";
      packageName = "rfdc";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rfdc/-/rfdc-1.4.1.tgz";
        sha512 = "q1b3N5QkRUWUl7iyylaaj3kOpIT0N2i9MqIEQXP73GVsN9cw3fdx8X63cEmWhJGi2PPCF23Ijp7ktmd39rawIA==";
      };
    };
    "semver-7.7.3" = {
      name = "semver";
      packageName = "semver";
      version = "7.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.7.3.tgz";
        sha512 = "SdsKMrI9TdgjdweUSR9MweHA4EJ8YxHn8DFaDisvhVlUOe4BF1tLD7GAj0lIqWVl+dPb/rExr0Btby5loQm20Q==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "tsx-4.20.6" = {
      name = "tsx";
      packageName = "tsx";
      version = "4.20.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/tsx/-/tsx-4.20.6.tgz";
        sha512 = "ytQKuwgmrrkDTFP4LjR0ToE2nqgy886GpvRSpU0JAnrdBYppuY5rLkRUYPU1yCryb24SsKBTL/hlDQAEFVwtZg==";
      };
    };
    "undici-6.22.0" = {
      name = "undici";
      packageName = "undici";
      version = "6.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/undici/-/undici-6.22.0.tgz";
        sha512 = "hU/10obOIu62MGYjdskASR3CUAiYaFTtC9Pa6vHyf//mAipSvSQg6od2CnJswq7fvzNS3zJhxoRkgNVaHurWKw==";
      };
    };
    "utf-8-validate-6.0.5" = {
      name = "utf-8-validate";
      packageName = "utf-8-validate";
      version = "6.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-6.0.5.tgz";
        sha512 = "EYZR+OpIXp9Y1eG1iueg8KRsY8TuT8VNgnanZ0uA3STqhHQTLwbl+WX76/9X5OY12yQubymBpaBSmMPkSTQcKA==";
      };
    };
    "ws-8.18.3" = {
      name = "ws";
      packageName = "ws";
      version = "8.18.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-8.18.3.tgz";
        sha512 = "PEIGCY5tSlUt50cqyMXfCzX+oOPqN0vuGqWzbcJ2xvnkzkq46oOpz7dQaTDBdfICb4N14+GARUDw2XV2N4tvzg==";
      };
    };
    "zod-3.25.76" = {
      name = "zod";
      packageName = "zod";
      version = "3.25.76";
      src = fetchurl {
        url = "https://registry.npmjs.org/zod/-/zod-3.25.76.tgz";
        sha512 = "gzUt/qt81nXsFGKIFcC3YnfEAx5NkunCfnDlvuBSSFS02bcXu4Lmea0AFIUwbLWxWPx3d9p8S5QoaujKcNQxcQ==";
      };
    };
  };
in
{
  hardhat = nodeEnv.buildNodePackage {
    name = "hardhat";
    packageName = "hardhat";
    version = "3.0.15";
    src = fetchurl {
      url = "https://registry.npmjs.org/hardhat/-/hardhat-3.0.15.tgz";
      sha512 = "cXxaeSxFJ+u0MfbvWsS3Gdr7/uP7wjo4xviYcGdu9AKtwY6YsU+v0quK/j1NWmvO1Y4gk350SdZzQw++hJy4LA==";
    };
    dependencies = [
      sources."@noble/curves-1.4.2"
      sources."@noble/hashes-1.4.0"
      sources."@nomicfoundation/edr-0.12.0-next.14"
      sources."@nomicfoundation/edr-darwin-arm64-0.12.0-next.14"
      sources."@nomicfoundation/edr-darwin-x64-0.12.0-next.14"
      sources."@nomicfoundation/edr-linux-arm64-gnu-0.12.0-next.14"
      sources."@nomicfoundation/edr-linux-arm64-musl-0.12.0-next.14"
      sources."@nomicfoundation/edr-linux-x64-gnu-0.12.0-next.14"
      sources."@nomicfoundation/edr-linux-x64-musl-0.12.0-next.14"
      sources."@nomicfoundation/edr-win32-x64-msvc-0.12.0-next.14"
      sources."@nomicfoundation/hardhat-errors-3.0.5"
      sources."@nomicfoundation/hardhat-utils-3.0.5"
      sources."@nomicfoundation/hardhat-zod-utils-3.0.1"
      sources."@nomicfoundation/solidity-analyzer-0.1.2"
      sources."@scure/base-1.1.9"
      sources."@scure/bip32-1.4.0"
      sources."@scure/bip39-1.3.0"
      sources."@sentry/core-9.47.1"
      sources."@streamparser/json-0.0.22"
      sources."@streamparser/json-node-0.0.22"
      sources."adm-zip-0.4.16"
      sources."ansi-colors-4.1.3"
      sources."ansi-regex-5.0.1"
      sources."bufferutil-4.0.9"
      sources."chalk-5.6.2"
      sources."chokidar-4.0.3"
      sources."debug-4.4.3"
      sources."enquirer-2.4.1"
      sources."env-paths-2.2.1"
      sources."esbuild-0.25.12"
      sources."ethereum-cryptography-2.2.1"
      sources."fast-equals-5.3.3"
      sources."get-tsconfig-4.13.0"
      sources."json-stream-stringify-3.1.6"
      (sources."micro-eth-signer-0.14.0" // {
        dependencies = [
          sources."@noble/curves-1.8.2"
          sources."@noble/hashes-1.7.2"
        ];
      })
      (sources."micro-packed-0.7.3" // {
        dependencies = [
          sources."@scure/base-1.2.6"
        ];
      })
      sources."ms-2.1.3"
      sources."node-gyp-build-4.8.4"
      sources."p-map-7.0.4"
      sources."readdirp-4.1.2"
      sources."resolve-pkg-maps-1.0.0"
      sources."resolve.exports-2.0.3"
      sources."rfdc-1.4.1"
      sources."semver-7.7.3"
      sources."strip-ansi-6.0.1"
      sources."tsx-4.20.6"
      sources."undici-6.22.0"
      sources."utf-8-validate-6.0.5"
      sources."ws-8.18.3"
      sources."zod-3.25.76"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Hardhat is an extensible developer tool that helps smart contract developers increase productivity by reliably bringing together the tools they want.";
      homepage = "https://github.com/nomicfoundation/hardhat/tree/v-next/v-next/hardhat";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
