# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "beautifulsoup4" = super.buildPythonPackage rec {
    pname = "beautifulsoup4";
    version = "4.14.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/fe/3aed5d0be4d404d12d36ab97e2f1791424d9ca39c2f754a6285d59a3b01d/beautifulsoup4-4.14.2-py3-none-any.whl";
      sha256 = "05a5dpgdba88hlrw5sf4pci1w2gdjw7md1b9ss489kmyihxgmxjy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."soupsieve"
      self."typing-extensions"
    ];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2025.11.12";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/70/7d/9bc192684cea499815ff478dfcdc13835ddf401365057044fb721ec6bddb/certifi-2025.11.12-py3-none-any.whl";
      sha256 = "0jrd0qnryi4mryf91nx6vgw0x0ppq8ppiv5pjqnmrg8b0f88gplp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "3.4.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/13/69/33ddede1939fdd074bce5434295f38fae7136463422fe4fd3e0e89b98062/charset_normalizer-3.4.4.tar.gz";
      sha256 = "06p20hsbfmg9pdc307ffnb7nwfmlwyw06dp4423z4d8w262pjlwl";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "colorama" = super.buildPythonPackage rec {
    pname = "colorama";
    version = "0.4.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl";
      sha256 = "1ijz53xpmxds2qf02l9yf0rnp7bznwh3ci4xkw8wmh5cyn8rj7ag";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0e/61/66938bbb5fc52dbdf84594873d5b51fb1f7c7794e9c0f5bd885f30bc507b/idna-3.11-py3-none-any.whl";
      sha256 = "1sipr9kdjcmwjm3lc6dx83qk6j4dq7lnyvhy15jazvwxkps8f6kp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mutagen" = super.buildPythonPackage rec {
    pname = "mutagen";
    version = "1.47.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b0/7a/620f945b96be1f6ee357d211d5bf74ab1b7fe72a9f1525aafbfe3aee6875/mutagen-1.47.0-py3-none-any.whl";
      sha256 = "06d7miq4z6m7j8rx2czkmqhgbjb2bwjagfz5v0wraylhqm86zngd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pathvalidate" = super.buildPythonPackage rec {
    pname = "pathvalidate";
    version = "3.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/70/875f4a23bfc4731703a5835487d0d2fb999031bd415e7d17c0ae615c18b7/pathvalidate-3.3.1-py3-none-any.whl";
      sha256 = "0pvkw714pvynqk51zzvcppgmppqpxqvm3yljc3wim3hzd6mvlqsj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pick" = super.buildPythonPackage rec {
    pname = "pick";
    version = "1.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/08/65/91ef9aed9f125f3d0bc37e9fb7694a7e13926cea7e6615853be141d86696/pick-1.6.0-py3-none-any.whl";
      sha256 = "05a6c3rvx69grl344055gvyjknrvinicg66i4f154vsqyp77sp7a";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "qobuz-dl" = super.buildPythonPackage rec {
    pname = "qobuz-dl";
    version = "0.9.9.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/a4/ec855fa6157a64c3c62086204442881f6ddf497f189fa4f3999f2190afff/qobuz_dl-0.9.9.10-py3-none-any.whl";
      sha256 = "0kfdxcqhdf80jj7gm7vj4fcbw32m3zcsyrvnhqhickrvq2fb1rj8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."beautifulsoup4"
      self."colorama"
      self."mutagen"
      self."pathvalidate"
      self."pick"
      self."requests"
      self."tqdm"
    ];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.32.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/db/4254e3eabe8020b458f1a747140d32277ec7a271daf1d235b70dc0b4e6e3/requests-2.32.5-py3-none-any.whl";
      sha256 = "1dpz38b6lnn8fcad7kfiagagbc3djy3f35a24qrdakx36x3gjqi4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "soupsieve" = super.buildPythonPackage rec {
    pname = "soupsieve";
    version = "2.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/14/a0/bb38d3b76b8cae341dad93a2dd83ab7462e6dbcdd84d43f54ee60a8dc167/soupsieve-2.8-py3-none-any.whl";
      sha256 = "0k4qqx5k8pvrzsma0pkwvjmybr1fmsj9hjp1ybbza80fldb69iqc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tqdm" = super.buildPythonPackage rec {
    pname = "tqdm";
    version = "4.67.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d0/30/dc54f88dd4a2b5dc8a0279bdd7270e735851848b762aeb1c1184ed1f6b14/tqdm-4.67.1-py3-none-any.whl";
      sha256 = "1qldljk9pzxx05b3xrh1xaih3n2c8vaq1mg0hhlfg0lg7355wi16";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.15.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/67/36e9267722cc04a6b9f15c7f3441c2363321a3ea07da7ae0c0707beb2a9c/typing_extensions-4.15.0-py3-none-any.whl";
      sha256 = "0j75qhcc0p627f464gd7kjcirdzcga5zl32a0w4ann2phk31kyph";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "2.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a7/c2/fe1e52489ae3122415c51f387e221dd0773709bad6c6cdaa599e8a2c5185/urllib3-2.5.0-py3-none-any.whl";
      sha256 = "1p7hrw2cc75zyqbb49diqi371gxkis07225mfkii6spsq1ridc76";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
