#!/usr/bin/env bash

set -e

NEW_VER="$(
	curl -fsSL https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest \
	   | grep ' *"tag_name": *"v[0-9][0-9.]*"' \
	   | sed 's/ *"tag_name": *"v\([0-9][0-9.]*\)".*/\1/'
)"

if [[ -f ${XDG_CACHE_HOME:-$HOME/.cache}/versions/obsidian ]]; then
	OLD_VER="$(cat ${XDG_CACHE_HOME:-$HOME/.cache}/versions/obsidian)"
else
	OLD_VER="0.0.0"
fi

if [[ "$NEW_VER" != "$OLD_VER" ]]; then
	if [[ "$ARCH" == "amd64" ]]; then
		curl -fsSL -o /tmp/obsidian.tar.gz \
		     "https://github.com/obsidianmd/obsidian-releases/releases/download/v${NEW_VER}/obsidian-${NEW_VER}.tar.gz"
	elif [[ "$ARCH" == "aarch64" ]]; then
		curl -fsSL -o /tmp/obsidian.tar.gz \
		     "https://github.com/obsidianmd/obsidian-releases/releases/download/v${NEW_VER}/obsidian-${NEW_VER}-arm64.tar.gz"
	fi

	tar -xzvf /tmp/obsidian.tar.gz -C /tmp
	if [[ ! -d $HOME/local/lib ]]; then
		mkdir -p $HOME/local/lib
	elif [[ -d $HOME/local/lib/obsidian ]]; then
		rm -rf $HOME/local/lib/obsidian
	fi
	mv /tmp/obsidian-* $HOME/local/lib/obsidian
	rm -f /tmp/obsidian.tar.gz

	mkdir -p ${XDG_CACHE_HOME:-$HOME/.cache}/versions
	echo "$NEW_VER" > ${XDG_CACHE_HOME:-$HOME/.cache}/versions/obsidian

	echo "Obsidian updated to v$NEW_VER"
else
	echo "Obsidian is already at v$NEW_VER"
fi
