#!/usr/bin/env bash

# Install additional tooling
#
echo "Installing additional tooling"

if [[ "$FLAVOR" == "macos" ]]; then
	brew install \
	     adobe-creative-cloud \
	     block-goose-cli \
	     bottom \
	     brave-browser \
	     calibre \
	     cd-discid \
	     charmbracelet/tap/glow \
	     claude \
	     curl \
	     diff-so-fancy \
	     discord \
	     doppler-app \
	     dos2unix \
	     duf \
	     dust \
	     eza \
	     fd \
	     ffmpeg \
	     fish \
	     font-jetbrains-mono-nerd-font \
	     fzf \
	     gawk \
	     ghc \
	     ghostscript \
	     git-delta \
	     github \
	     gnupg \
	     google-drive \
	     homebrew/cask/handbrake \
	     imagemagick \
	     jpeg-turbo \
	     jq \
	     libyaml \
	     less \
	     makemkv \
	     msgpack-tools \
	     normalize \
	     obsidian \
	     openssh \
	     optipng \
	     pandoc \
	     pinentry-mac \
	     poppler \
	     procs \
	     proton-drive \
	     proton-mail \
	     proton-pass \
	     protonvpn \
	     pstree \
	     qflipper \
	     qobuz-downloader \
	     rclone \
	     reader \
	     ripgrep \
	     rsgain \
	     rsync \
	     rust \
	     scroll-reverser \
	     signal \
	     slack \
	     sqlite \
	     starship \
	     stellarium \
	     todoist-app \
	     tresorit \
	     uutils-coreutils \
	     uutils-diffutils \
	     uutils-findutils \
	     vlc \
	     wezterm \
	     xz \
	     yamlresume \
	     yubico-yubikey-manager \
	     zoxide \
	     zstd

	# The following packages need to be built from source to avoid
	# library API mis-matches
	#
	brew install --build-from-source \
	     abcde
elif [[ "$FLAVOR" == "debian" ]]; then
	sudo mkdir -p /usr/share/keyrings

	sudo curl -fsSLo \
	     /usr/share/keyrings/brave-browser-archive-keyring.gpg \
	     https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
	sudo tee /etc/apt/sources.list.d/brave-browser.sources > /dev/null <<- EOF
		Types: deb
		URIs: https://brave-browser-apt-release.s3.brave.com
		Suites: stable
		Components: main
		Architectures: amd64 arm64
		Signed-By: /usr/share/keyrings/brave-browser-archive-keyring.gpg
		EOF

	curl -fsSL https://apt.fury.io/wez/gpg.key | \
		sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
	sudo tee /etc/apt/sources.list.d/wezterm.list > /dev/null <<- EOF
		deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *
		EOF

	sudo apt update
	sudo apt install -y \
	         build-essential \
	         curl \
	         dialog \
	         file \
	         git \
	         gnupg \
	         procps
	sudo apt install -y \
	         apt-utils \
	         brave-browser \
	         calibre \
	         eject \
	         fonts-noto \
	         gnome-keyring \
	         handbrake \
	         man-db \
	         podman \
	         tigervnc-standalone-server \
	         uuid-runtime \
	         unzip \
	         wezterm \
	         xdg-utils \
	         xdg-user-dirs \
	         xfce4 \
	         yubikey-manager-qt \
	         zip

	brew install \
	     block-goose-cli \
	     bottom \
	     cd-discid \
	     charmbracelet/tap/glow \
	     curl \
	     diff-so-fancy \
	     dos2unix \
	     duf \
	     dust \
	     eza \
	     fd \
	     ffmpeg \
	     fish \
	     fzf \
	     gawk \
	     ghc \
	     ghostscript \
	     git-delta \
	     imagemagick \
	     jpeg-turbo \
	     jq \
	     less \
	     libyaml \
	     msgpack-tools \
	     normalize \
	     openssh \
	     optipng \
	     pandoc \
	     poppler \
	     procs \
	     rclone \
	     ripgrep \
	     rsgain \
	     rsync \
	     rust \
	     sqlite \
	     starship \
	     uutils-coreutils \
	     uutils-diffutils \
	     uutils-findutils \
	     xclip \
	     xz \
	     yamlresume \
	     zoxide \
	     zstd

	# The following packages need to be built from source to avoid
	# library API mis-matches
	#
	brew install --build-from-source \
	     abcde

	# Additional "manual" installs
	#
	$HOME/local/lib/linux/common/libexec/update-jetbrains-mono

	# Disposable Kali
	#
	#$HOME/local/lib/linux/common/bin/kali --install

	# System-level tweaks
	#
	sudo ln -sf /usr/share/zoneinfo/America/Denver /etc/localtime

	sudo systemctl stop lightdm.service
	sudo systemctl disable lightdm.service

	if [[ $(grep -c "$USER" /etc/tigervnc/vncserver.users) -eq 0 ]]; then
		echo ":0=$USER" | sudo tee -a /etc/tigervnc/vncserver.users
	fi

	# Disable some background services to try to avoid filesystem
	# corruption in the Android Debian VM as of 2025-09-21; ideally
	# these will be re-enabled when (if?) that environment becomes
	# more stable
	#
	sudo systemctl stop podman-auto-update.service
	sudo systemctl stop podman-auto-update.timer
	sudo systemctl stop podman-restart.service
	sudo systemctl stop podman.service
	sudo systemctl stop podman.socket

	sudo systemctl disable podman-auto-update.service
	sudo systemctl disable podman-auto-update.timer
	sudo systemctl disable podman-restart.service
	sudo systemctl disable podman.service
	sudo systemctl disable podman.socket
fi

# Set up directories and symlinks
#
echo "Symlinking dotfiles and directories"

touch $XDG_CONFIG_HOME/rclone/rclone.conf

if [[ -d $HOME/.cache ]] && [[ ! -L $HOME/.cache ]]; then
	mv -v $HOME/.cache $XDG_CACHE_HOME
elif [[ ! -e $HOME/.cache ]]; then
	mkdir -p $XDG_CACHE_HOME
fi
if [[ ! -e $HOME/.cache ]]; then
	ln -sf $XDG_CACHE_HOME $HOME/.cache
fi

if [[ -d $HOME/.config ]] && [[ ! -L $HOME/.config ]]; then
	cp -anv $HOME/.config/* $XDG_CONFIG_HOME/ || true
	rm -rf  $HOME/.config
fi
if [[ ! -e $HOME/.config ]]; then
	ln -sf  $XDG_CONFIG_HOME $HOME/.config
fi

if [[ -d $HOME/.local/bin ]] && [[ ! -L $HOME/.local/bin ]]; then
	cp -anv $HOME/.local/bin/* $HOME/bin/ || true
	rm -rf  $HOME/.local/bin
fi
if [[ ! -e $HOME/local/bin ]]; then
	ln -sf  $HOME/bin $HOME/local/bin
fi

if [[ -d $HOME/.local ]] && [[ ! -L $HOME/.local ]]; then
	cp -anv $HOME/.local/* $HOME/local/ || true
	rm -rf  $HOME/.local
fi
if [[ ! -e $HOME/.local ]]; then
	ln -sf  $HOME/local $HOME/.local
fi
if [[ ! -e $HOME/.var ]]; then
	ln -sf  $HOME/local $HOME/.var
fi

# Set up XDG user directories
#
echo "Setting up XDG directories"

cat > config/user-dirs.dirs << EOF
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run.
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
#
EOF
if [[ "$OS" == "macos" ]]; then
	cat >> config/user-dirs.dirs <<- EOF
	XDG_DESKTOP_DIR="\$HOME/Desktop"
	XDG_DOCUMENTS_DIR="\$HOME/Documents"
	XDG_DOWNLOAD_DIR="\$HOME/Downloads"
	XDG_MUSIC_DIR="\$HOME/Music"
	XDG_PICTURES_DIR="\$HOME/Pictures"
	XDG_PUBLICSHARE_DIR="\$HOME/Public"
	XDG_TEMPLATES_DIR="\$HOME/Documents/Templates"
	XDG_VIDEOS_DIR="\$HOME/Movies"
	EOF
elif [[ "$OS" == "linux" ]]; then
	cat >> config/user-dirs.dirs <<- EOF
	XDG_DESKTOP_DIR="\$HOME/data/desktop"
	XDG_DOCUMENTS_DIR="\$HOME/data"
	XDG_DOWNLOAD_DIR="\$HOME/downloads"
	XDG_MUSIC_DIR="\$HOME/data/music"
	XDG_PICTURES_DIR="\$HOME/data/pictures"
	XDG_PUBLICSHARE_DIR="\$HOME/public"
	XDG_TEMPLATES_DIR="\$HOME/data/templates"
	XDG_VIDEOS_DIR="\$HOME/data/videos"
	EOF
fi

source config/user-dirs.dirs

if [[ ! -d "$XDG_DOCUMENTS_DIR" ]]; then
	mkdir -p "$XDG_DOCUMENTS_DIR"
	if [[ -d "$HOME/Documents" ]] \
	&& [[ "$XDG_DOCUMENTS_DIR" != "$HOME/Documents" ]]; then
		cp -anv "$HOME/Documents"/* "$XDG_DOCUMENTS_DIR"/ || true
		rm -rf  "$HOME/Documents"
	fi
fi

if [[ ! -d "$XDG_DESKTOP_DIR" ]]; then
	mkdir -p "$XDG_DESKTOP_DIR"
	if [[ -d "$HOME/Desktop" ]] \
	&& [[ "$XDG_DESKTOP_DIR" != "$HOME/Desktop" ]]; then
		cp -anv "$HOME/Desktop"/* "$XDG_DESKTOP_DIR"/ || true
		rm -rf  "$HOME/Desktop"
	fi
fi

if [[ ! -d "$XDG_DOWNLOAD_DIR" ]]; then
	if [[ "$USER" == "droid" ]] && [[ -d /mnt/shared ]]; then
		ln -sf /mnt/shared "$XDG_DOWNLOAD_DIR"
	else
		mkdir -p "$XDG_DOWNLOAD_DIR"
	fi
	if [[ -d "$HOME/Downloads" ]] \
	&& [[ "$XDG_DOWNLOAD_DIR" != "$HOME/Downloads" ]]; then
		cp -anv "$HOME/Downloads"/* "$XDG_DOWNLOAD_DIR"/ || true
		rm -rf  "$HOME/Downloads"
	fi
fi

if [[ ! -d "$XDG_MUSIC_DIR" ]]; then
	mkdir -p "$XDG_MUSIC_DIR"
	if [[ -d "$HOME/Music" ]] \
	&& [[ "$XDG_MUSIC_DIR" != "$HOME/Music" ]]; then
		cp -anv "$HOME/Music"/* "$XDG_MUSIC_DIR"/ || true
		rm -rf  "$HOME/Music"
	fi
fi

if [[ ! -d "$XDG_PICTURES_DIR" ]]; then
	mkdir -p "$XDG_PICTURES_DIR"
	if [[ -d "$HOME/Pictures" ]] \
	&& [[ "$XDG_PICTURES_DIR" != "$HOME/Pictures" ]]; then
		cp -anv "$HOME/Pictures"/* "$XDG_PICTURES_DIR"/ || true
		rm -rf  "$HOME/Pictures"
	fi
fi

if [[ ! -d "$XDG_PUBLICSHARE_DIR" ]]; then
	mkdir -p "$XDG_PUBLICSHARE_DIR"
	if [[ -d "$HOME/Public" ]] \
	&& [[ "$XDG_PUBLICSHARE_DIR" != "$HOME/Public" ]]; then
		cp -anv "$HOME/Public"/* "$XDG_PUBLICSHARE_DIR"/ || true
		rm -rf  "$HOME/Public"
	fi
fi

if [[ ! -d "$XDG_TEMPLATES_DIR" ]]; then
	mkdir -p "$XDG_TEMPLATES_DIR"
	if [[ -d "$HOME/Templates" ]] \
	&& [[ "$XDG_TEMPLATES_DIR" != "$HOME/Templates" ]]; then
		cp -anv "$HOME/Templates"/* "$XDG_TEMPLATES_DIR"/ || true
		rm -rf  "$HOME/Templates"
	fi
fi

if [[ ! -d "$XDG_VIDEOS_DIR" ]]; then
	mkdir -p "$XDG_VIDEOS_DIR"
	if [[ -d "$HOME/Videos" ]] \
	&& [[ "$XDG_VIDEOS_DIR" != "$HOME/Videos" ]]; then
		cp -anv "$HOME/Videos"/* "$XDG_VIDEOS_DIR"/ || true
		rm -rf  "$HOME/Videos"
	fi
fi

# Xfce panel setup
#
if [[ "$OS" == "linux" ]]; then
	mkdir -p "$XDG_CONFIG_HOME/xfce4/xfconf/xfce-perchannel-xml"

	cat > "$XDG_CONFIG_HOME/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml" <<- EOF
	<?xml version="1.0" encoding="UTF-8"?>

	<channel name="xfce4-panel" version="1.0">
	  <property name="configver" type="int" value="2"/>
	  <property name="panels" type="array">
	    <value type="int" value="1"/>
	    <property name="dark-mode" type="bool" value="true"/>
	    <property name="panel-1" type="empty">
	      <property name="position" type="string" value="p=6;x=949;y=24"/>
	      <property name="length" type="double" value="100"/>
	      <property name="position-locked" type="bool" value="true"/>
	      <property name="icon-size" type="uint" value="16"/>
	      <property name="size" type="uint" value="26"/>
	      <property name="plugin-ids" type="array">
	        <value type="int" value="1"/>
	        <value type="int" value="2"/>
	        <value type="int" value="5"/>
	        <value type="int" value="6"/>
	        <value type="int" value="8"/>
	        <value type="int" value="10"/>
	        <value type="int" value="11"/>
	        <value type="int" value="12"/>
	        <value type="int" value="13"/>
	      </property>
	    </property>
	  </property>
	  <property name="plugins" type="empty">
	    <property name="plugin-1" type="string" value="applicationsmenu"/>
	    <property name="plugin-2" type="string" value="tasklist">
	      <property name="grouping" type="uint" value="1"/>
	      <property name="flat-buttons" type="bool" value="true"/>
	    </property>
	    <property name="plugin-5" type="string" value="separator">
	      <property name="style" type="uint" value="0"/>
	      <property name="expand" type="bool" value="true"/>
	    </property>
	    <property name="plugin-6" type="string" value="systray">
	      <property name="square-icons" type="bool" value="true"/>
	      <property name="icon-size" type="int" value="16"/>
	      <property name="single-row" type="bool" value="true"/>
	      <property name="symbolic-icons" type="bool" value="true"/>
	    </property>
	    <property name="plugin-8" type="string" value="pulseaudio">
	      <property name="enable-keyboard-shortcuts" type="bool" value="true"/>
	      <property name="show-notifications" type="bool" value="true"/>
	    </property>
	    <property name="plugin-10" type="string" value="notification-plugin"/>
	    <property name="plugin-11" type="string" value="separator">
	      <property name="style" type="uint" value="0"/>
	    </property>
	    <property name="plugin-12" type="string" value="clock">
	      <property name="digital-layout" type="uint" value="2"/>
	      <property name="digital-date-font" type="string" value="JetBrainsMono Nerd Font 10"/>
	      <property name="digital-date-format" type="string" value="%Y-%m-%d @ %H:%M"/>
	      <property name="tooltip-format" type="string" value="%A %B %d, %Y"/>
	    </property>
	    <property name="plugin-13" type="string" value="separator">
	      <property name="style" type="uint" value="0"/>
	    </property>
	  </property>
	</channel>
	EOF
fi

# Calibre pre-setup
#
if [[ "$OS" == "macos" ]]; then
	mkdir -p $HOME/Library/Preferences/calibre
else
	mkdir -p $XDG_CONFIG_HOME/calibre
fi
mkdir -p $HOME/data/calibre

# The Debian Bookworm gpg-agent seems to need absolute paths in its
# configuration file, but later versions of gpg-agent can use `~` for
# $HOME.
#
# In any case, we must generate ~/.gnupg/gpg-agent.conf by hand.
#
mkdir -p $HOME/.gnupg
if [[ "$FLAVOR" == "debian" ]]; then
	echo "pinentry-program $HOME/bin/pinentry" > $HOME/.gnupg/gpg-agent.conf
else
	echo "pinentry-program ~/bin/pinentry" > $HOME/.gnupg/gpg-agent.conf
fi
echo "enable-ssh-support" >> $HOME/.gnupg/gpg-agent.conf

# Fix permissions
#
chmod 700 $HOME/.ssh
find $HOME/.ssh -type d -exec chmod 700 "{}" \;
find $HOME/.ssh -type f -exec chmod 600 "{}" \;

chmod 700 $HOME/.gnupg
find $HOME/.gnupg -type d -exec chmod 700 "{}" \;
find $HOME/.gnupg -type f -exec chmod 600 "{}" \;

# Need to set up GPG environment here to work around issues on some
# systems
#
export GPG_TTY=$(tty)
export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
gpgconf --kill gpg-agent
gpg-connect-agent updatestartuptty /bye

# Set up GPG and SSH, if applicable
#
if [[ $(ls -1 $HOME/.ssh/id_* 2> /dev/null | wc -l) -eq 0 ]] \
&& [[ $(gpg --list-secret-keys --with-colons \
              | grep -cE '^sec:(f|u):') -eq 0 ]]; then
	echo "Setting up initial SSH and GPG keys"

	# Create a new GPG/SSH keys
	#
	gpg --batch --expert --full-generate-key <<- EOF
	Key-Type: EDDSA
		Key-Curve: ed25519
		Key-Usage: sign auth
	Subkey-Type: ECDH
		Subkey-Curve: cv25519
		Subkey-Usage: encrypt
	Expire-Date: 4m
	Name-Real: Nathan Acks
	Name-Email: nathan.acks@cardboard-iguana.com
	EOF

	# Get the key ID of the new key
	#
	NEW_SECRET_KEY_ID="$(
		gpg --list-secret-keys --with-colons \
		| grep -E '^sec:(f|u):' \
		| cut -d: -f 5
	)"

	# Get the keygrip of the new key
	#
	# FIXME: I *think* that the output of --with-colons is ordered, and
	#        thus the keygrip for the primary key is just the first
	#        keygrip when this key is displayed. But I can't find any
	#        good documentation about this, so I may be wrong and this
	#        may break.
	#
	NEW_SECRET_KEY_GRIP="$(
		gpg --list-secret-keys --with-colons $NEW_SECRET_KEY_ID \
		| grep -E '^grp:' \
		| cut -d: -f 10 \
		| head -1
	)"

	# SSH setup
	#
	gpgconf --kill gpg-agent
	rm -f "$HOME"/.gnupg/sshcontrol
	gpg-connect-agent updatestartuptty /bye &> /dev/null
	ssh-add -l &> /dev/null || true
	gpg-connect-agent "keyattr $NEW_SECRET_KEY_GRIP Use-for-ssh: true" /bye > /dev/null
	echo "$NEW_SECRET_KEY_GRIP" >> "$HOME"/.gnupg/sshcontrol

	# Update git signing key
	#
	echo "[user]" > $XDG_CONFIG_HOME/git/gpg.ini
	echo "	signingkey = $NEW_SECRET_KEY_ID" >> $XDG_CONFIG_HOME/git/gpg.ini

	# Print public GPG and SSH keys for new secret key
	#
	echo ""
	echo "-----------------------------------------"
	echo "New secret key 0x$NEW_SECRET_KEY_ID created"
	echo "-----------------------------------------"
	echo ""
	gpg --list-keys --with-keygrip --keyid-format=long $NEW_SECRET_KEY_ID
	echo "GPG public key block:"
	echo ""
	gpg --armor --export $NEW_SECRET_KEY_ID
	echo ""
	echo "SSH public key:"
	echo ""
	gpg --export-ssh-key $NEW_SECRET_KEY_ID
	echo ""
	echo "You must add the public GPG and SSH key displayed above to GitHub before"
	echo "continuing."
	echo ""
	read -rs -n 1 -p "Press any key to continue once this step is complete."
	echo ""
fi

# Check out a few useful code repositories
#
echo "Making some useful code repositories available"
mkdir -p $HOME/src
(
	cd $HOME/src

	if [[ ! -d smart-contracts-hacking ]]; then
		git clone --recurse-submodules \
		    git@github.com:cardboard-iguana/smart-contracts-hacking.git
	fi
	if [[ ! -d resume ]]; then
		git clone --recurse-submodules \
		    git@github.com:necopinus/resume.git
	fi
	if [[ ! -d website-theme ]]; then
		git clone --recurse-submodules \
		    git@github.com:necopinus/website-theme.git
	fi

	if [[ ! -d backups ]]; then
		git clone --recurse-submodules \
		    git@github.com:The-Yak-Collective/backups.git
	fi
	if [[ ! -d GPTDiscord ]]; then
		git clone --recurse-submodules \
		    git@github.com:The-Yak-Collective/GPTDiscord.git
	fi
	if [[ ! -d yakcollective ]]; then
		git clone --recurse-submodules \
		    git@github.com:The-Yak-Collective/yakcollective.git
	fi

	if [[ ! -d cardboard-iguana.com ]]; then
		git clone --recurse-submodules \
		    git@github.com:cardboard-iguana/cardboard-iguana.com.git
	fi
	if [[ ! -d chateaumaxmin.info ]]; then
		git clone --recurse-submodules \
		    git@github.com:necopinus/chateaumaxmin.info.git
	fi
	if [[ ! -d delphi-strategy.com ]]; then
		git clone --recurse-submodules \
		    git@github.com:necopinus/delphi-strategy.com.git
	fi
	if [[ ! -d digital-orrery.com ]]; then
		git clone --recurse-submodules \
		    git@github.com:necopinus/digital-orrery.com.git
	fi
	if [[ ! -d necopinus.xyz ]]; then
		git clone --recurse-submodules \
		    git@github.com:necopinus/necopinus.xyz.git
	fi

	if [[ ! -d twitter-archive-parser ]]; then
		git clone --recurse-submodules \
		    https://github.com/timhutton/twitter-archive-parser.git
	fi
)

# Install Helix grammars
#
# NOTE: This must be done *after* git is setup!
#
hx -g fetch
hx -g build

# Try (probably futilely) to keep environment variables in sync with the
# garbage fire that is systemd
#
if [[ "$OS" == "linux" ]]; then
	$HOME/local/lib/linux/common/libexec/update-environment
fi

# Try (probably futile) to guard against filesystem corruption in the
# Android Debian VM
#
sync

# A reboot is STRONGLY recommended
#
echo ""
echo "Configuration complete!"
echo ""
echo "It is STRONGLY recommended that you reboot your system NOW."
