#!/usr/bin/env bash

# Install additional tooling
#
echo "Installing additional tooling"

if [[ "$FLAVOR" == "macos" ]]; then
    brew install \
        fish \
        wezterm
elif [[ "$FLAVOR" == "debian" ]]; then
    sudo mkdir -p /usr/share/keyrings

    curl -fsSL https://apt.fury.io/wez/gpg.key |
        sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
    sudo tee /etc/apt/sources.list.d/wezterm.list >/dev/null <<-EOF
		deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *
		EOF

    sudo apt install -y \
        wezterm

    brew install \
        fish

    # System-level tweaks
    #
    sudo ln -sf /usr/share/zoneinfo/America/Denver /etc/localtime

    sudo systemctl stop lightdm.service
    sudo systemctl disable lightdm.service

    if [[ $(grep -c "$USER" /etc/tigervnc/vncserver.users) -eq 0 ]]; then
        echo ":0=$USER" | sudo tee -a /etc/tigervnc/vncserver.users
    fi
fi
