#!/usr/bin/env bash

# Personal > Appearance
xfconf-query --create -c "xsettings" -p "/Net/ThemeName" --type "string" --set "Adwaita-dark"
xfconf-query --create -c "xsettings" -p "/Net/IconThemeName" --type "string" --set "Adwaita"
xfconf-query --create -c "xsettings" -p "/Gtk/FontName" --type "string" --set "Noto Sans 10"
xfconf-query --create -c "xsettings" -p "/Gtk/MonospaceFontName" --type "string" --set "JetBrainsMono Nerd Font 10"

# Personal > Desktop

xfconf-query --create -c "xfce4-desktop" -p "/desktop-icons/style" --type "int" --set "0"

for BACKDROP_PATH in $(xfconf-query -c xfce4-desktop -lv | grep last-image | sed "s#/last-image.*##" | xargs); do
	xfconf-query --create -c "xfce4-desktop" -p "$BACKDROP_PATH/last-image" --type "string" --set "/usr/share/backgrounds/xfce/xfce-leaves.svg"
	xfconf-query --create -c "xfce4-desktop" -p "$BACKDROP_PATH/color-style" --type "int" --set "0"
	xfconf-query --create -c "xfce4-desktop" -p "$BACKDROP_PATH/rgba1" --type "double" --set "0.23921568627450981" --type "double" --set "0.2196078431372549" --type "double" --set "0.27450980392156865" --type "double" --set "1"
done

# Personal > File Manager Settings
xfconf-query --create -c "thunar" -p "/misc-text-beside-icons" --type "bool" --set "true"
xfconf-query --create -c "thunar" -p "/misc-full-path-in-tab-title" --type "bool" --set "true"

# Personal > Workspaces
xfconf-query --create -c "xfwm4" -p "/general/workspace_count" --type "int" --set "1"

# Hardware > Mouse and Touchpad
xfconf-query --create -c "xsettings" -p "/Gtk/CursorThemeName" --type "string" --set "Adwaita"

# System > Sessions and Startup
xfconf-query --create -c "xfce4-session" -p "/general/PromptOnLogout" --type "bool" --set "false"
