#!/usr/bin/env bash

set -e

NEW_VER="$(
	curl -fsSL https://api.github.com/repos/kovidgoyal/kitty/releases/latest \
	   | grep ' *"tag_name": *"v[0-9][0-9.]*"' \
	   | sed 's/ *"tag_name": *"v\([0-9][0-9.]*\)".*/\1/'
)"

if [[ -f ${XDG_CACHE_HOME:-$HOME/.cache}/versions/kitty ]]; then
	OLD_VER="$(cat ${XDG_CACHE_HOME:-$HOME/.cache}/versions/kitty)"
else
	OLD_VER="0.0.0"
fi

if [[ "$NEW_VER" != "$OLD_VER" ]]; then
	curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin dest=$HOME/local/lib launch=n

	mkdir -p ${XDG_CACHE_HOME:-$HOME/.cache}/versions
	echo "$NEW_VER" > ${XDG_CACHE_HOME:-$HOME/.cache}/versions/kitty

	echo "kitty updated to v$NEW_VER"
else
	echo "kitty is already at v$NEW_VER"
fi
