# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: claude:claude-opus-4-20250514:thinking
wrap: auto
light_theme: true
clients:
  - type: claude
  - type: openai
  - type: gemini
    patch:
      chat_completions:
        '.*':
          body:
            safetySettings:
              - category: HARM_CATEGORY_HARASSMENT
                threshold: BLOCK_NONE
              - category: HARM_CATEGORY_HATE_SPEECH
                threshold: BLOCK_NONE
              - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
                threshold: BLOCK_NONE
              - category: HARM_CATEGORY_DANGEROUS_CONTENT
                threshold: BLOCK_NONE
