# Abuse Debian's automatic sourcing of ~/.bash_aliases to override
# various configuration defaults.

# Make sure that ~/.local/bin is added to our path. We save the old path
# so that we can restore it at the end of this file if we're (1) on a
# Debian-derived OS and (2) we're running a login shell, since the
# default Debian ~/.profile blindly adds ~/.local/bin in this case.
#
if [[ -d $HOME/.local/bin ]]; then
	OLD_PATH="$PATH"
	export PATH="$HOME/.local/bin:$PATH"
fi

# Set custom configuration path.
#
if [[ -n "$(which gam)" ]]; then
	export GAMUSERCONFIGDIR="$HOME/.gam"
fi

# Backup GAM configuration data.
#
if [[ -d "$GAMUSERCONFIGDIR" ]] && [[ -d "/mnt/chromeos/GoogleDrive/MyDrive/gam" ]]; then
	rsync -acq --delete --force "$GAMUSERCONFIGDIR/" /mnt/chromeos/GoogleDrive/MyDrive/gam/
fi

# Start GNOME Keyring on Chrome OS.
#
if [[ "$HOSTNAME" == "penguin" ]]; then
	eval $(gnome-keyring-daemon --daemonize --start 2> /dev/null)
	export SSH_AUTH_SOCK
fi

# Start ssh-agent on Kali (when logging in on console).
#
if [[ "$HOSTNAME" == "kali" ]]; then
	if [[ $(pgrep -u "$USER" -c ssh-agent) -eq 0 ]]; then
		ssh-agent > "$XDG_RUNTIME_DIR/ssh-agent.env"
	fi
	if [[ -f "$XDG_RUNTIME_DIR/ssh-agent.env" ]] && [[ -z "$SSH_AUTH_SOCK" ]]; then
		source "$XDG_RUNTIME_DIR/ssh-agent.env"
	fi
fi

# Make sure that GPG TTY is set right when SSHing into Kali.
#
if [[ "$HOSTNAME" == "kali" ]] && [[ -z "$DISPLAY" ]]; then
	export GPG_TTY=$(tty)
	GPG_AGENT_COMMAND="gpg-connect-agent updatestartuptty /bye > /dev/null"
	if [[ ! " ${PROMPT_COMMAND[*]} " =~ " $GPG_AGENT_COMMAND " ]]; then
		PROMPT_COMMAND+=("$GPG_AGENT_COMMAND")
		export PROMPT_COMMAND
	fi
fi

# Add SSH identities.
#
if [[ -n "$SSH_AUTH_SOCK" ]] && [[ "$(ssh-add -L)" = "The agent has no identities." ]]; then
	ssh-add
fi

# Rationalize $HISTSIZE and $HISTFILESIZE.
#
if [[ -n "$HISTSIZE" ]] && [[ -n "$HISTFILESIZE" ]]; then
	if [[ $HISTSIZE -gt 0 ]] && [[ $HISTFILESIZE -gt 0 ]]; then
		if [[ $HISTSIZE -gt $HISTFILESIZE ]]; then
			export HISTFILESIZE=$HISTSIZE
		else
			export HISTSIZE=$HISTFILESIZE
		fi
	fi
fi

# Aliases.
#
if [[ -n "$(which msfconsole)" ]]; then
	alias msfconsole="env GO111MODULE=off msfconsole"
fi
if [[ -n "$(which insync-headless)" ]]; then
	alias insync-headless="env TERM=xterm insync-headless"
fi

# Restore OLD_PATH if this is a Debian-derived distribution to prevent
# ~/.local/bin from being doubled-up in our final PATH.
#
if [[ -f /etc/os-release ]]; then
	source /etc/os-release
fi
if [[ "$ID" = "debian" ]] || [[ "$ID_LIKE" =~ "debian" ]]; then
	if [[ -n "$OLD_PATH" ]] && [[ "$PATH" =~ "$HOME/.local/bin" ]]; then
		shopt -q login_shell && export PATH="$OLD_PATH"
		unset OLD_PATH
	fi
fi
