# Abuse Debian's automatic sourcing of ~/.bash_aliases to override
# various configuration defaults.

# Pull GAM configuration data and set custom path.
#
if [[ -d "/mnt/chromeos/GoogleDrive/MyDrive/gam" ]]; then
	rsync -aq --delete --force /mnt/chromeos/GoogleDrive/MyDrive/gam/ $HOME/.gam/
fi
export GAMUSERCONFIGDIR="$HOME/.gam"

# Start GNOME Keyring on Chrome OS.
#
source /etc/os-release
if [[ -n "$DISPLAY" ]] && [[ "$ID" == "debian" ]]; then
	eval $(gnome-keyring-daemon --start)
	export SSH_AUTH_SOCK
fi

# Rationalize $HISTSIZE and $HISTFILESIZE.
#
if [[ -n "$HISTSIZE" ]] && [[ -n "$HISTFILESIZE" ]]; then
	if [[ $HISTSIZE -gt 0 ]] && [[ $HISTFILESIZE -gt 0 ]]; then
		if [[ $HISTSIZE -gt $HISTFILESIZE ]]; then
			export HISTFILESIZE=$HISTSIZE
		else
			export HISTSIZE=$HISTFILESIZE
		fi
	fi
fi
