# Abuse Debian's automatic sourcing of ~/.bash_aliases to override
# various configuration defaults.

# Set custom configuration path.
#
export GAMUSERCONFIGDIR="$HOME/.gam"

# Backup GAM configuration data.
#
if [[ -d "$GAMUSERCONFIGDIR" ]] && [[ -d "/mnt/chromeos/GoogleDrive/MyDrive/gam" ]]; then
	rsync -acq --delete --force "$GAMUSERCONFIGDIR/" /mnt/chromeos/GoogleDrive/MyDrive/gam/
fi

# Start GNOME Keyring on Chrome OS.
#
if [[ "$HOSTNAME" == "penguin" ]]; then
	eval $(gnome-keyring-daemon --daemonize --start 2> /dev/null)
	export SSH_AUTH_SOCK
fi

# Start ssh-agent on Kali (when logging in on console).
#
if [[ "$HOSTNAME" == "kali" ]]; then
	if [[ $(pgrep -u "$USER" -c ssh-agent) -eq 0 ]]; then
		ssh-agent > "$XDG_RUNTIME_DIR/ssh-agent.env"
	fi
	if [[ -f "$XDG_RUNTIME_DIR/ssh-agent.env" ]]; then
		if [[ -z "$SSH_AUTH_SOCK" ]]; then
			source "$XDG_RUNTIME_DIR/ssh-agent.env"
		fi
		if [[ "$(ssh-add -L)" = "The agent has no identities." ]]; then
			ssh-add
		fi
	fi
fi

# Make sure that GPG TTY is set right when SSHing into Kali.
#
if [[ "$HOSTNAME" == "kali" ]] && [[ -z "$DISPLAY" ]]; then
	export GPG_TTY=$(tty)
	GPG_AGENT_COMMAND="gpg-connect-agent updatestartuptty /bye > /dev/null"
	if [[ ! " ${PROMPT_COMMAND[*]} " =~ " $GPG_AGENT_COMMAND " ]]; then
		PROMPT_COMMAND+=("$GPG_AGENT_COMMAND")
		export PROMPT_COMMAND
	fi
fi

# Make sure that ~/.local/bin is added to our path. Note that we only do
# this if we're *not* in a login shell, since the Debian default
# ~/.profile (which all of the distros I'm currently using inherit) adds
# this component blindly.
#
if [[ -d $HOME/.local/bin ]] && [[ ! "$PATH" =~ "$HOME/.local/bin" ]]; then
	shopt -q login_shell || export PATH="$HOME/.local/bin:$PATH"
fi

# Rationalize $HISTSIZE and $HISTFILESIZE.
#
if [[ -n "$HISTSIZE" ]] && [[ -n "$HISTFILESIZE" ]]; then
	if [[ $HISTSIZE -gt 0 ]] && [[ $HISTFILESIZE -gt 0 ]]; then
		if [[ $HISTSIZE -gt $HISTFILESIZE ]]; then
			export HISTFILESIZE=$HISTSIZE
		else
			export HISTSIZE=$HISTFILESIZE
		fi
	fi
fi
