# ~/.bash_logout: executed by bash(1) when login shell exits.

# Backup GAM configuration data.
#
if [[ -d "$HOME/.gam" ]] && [[ -d "/mnt/chromeos/GoogleDrive/MyDrive/gam" ]]; then
	rsync -aq --delete --force $HOME/.gam/ /mnt/chromeos/GoogleDrive/MyDrive/gam/
fi

# When leaving the console clear the screen to increase privacy.
#
if [[ "$SHLVL" -eq 1 ]]; then
	[[ -x /usr/bin/clear_console ]] && /usr/bin/clear_console -q
fi
