# Executed by all Zsh invocations. Must NOT include interactive commands
# or commands that produce any output. See:
#
#     https://medium.com/@rajsek/zsh-bash-startup-files-loading-order-bashrc-zshrc-etc-e30045652f2e

# Set up path, if applicable.
#
if [[ ! -o login ]]; then
	source $HOME/.zpath
fi

# Custom aliases.
#
if [[ -n "$(which msfconsole)" ]]; then
	alias msfconsole="env GO111MODULE=off msfconsole"
fi
